# Generated by Django 4.1.3 on 2023-04-26 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderanalysis',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carService.district', verbose_name='Район'),
        ),
    ]
